newsite/catalog/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	url('', views.index, name='index'),
	url(r'^books/$', views.BookListView.as_view(), name='books'),
    url(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),

]

newsite/newsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls')),
    url(r'^$', RedirectView.as_view(url='/catalog/', permanent=True))
] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

newsite/catalog/models.py
from django.db import models
from django.urls import reverse 
import uuid 
# Create your models here.

class Genre(models.Model):
	"""docstring for Genre"""
	name = models.CharField(max_length=200, help_text='Enter a book genre')

	def __str__(self):
		return self.name


class book(models.Model):

	title = models.CharField(max_length = 200)
	author = models.ForeignKey('Author', on_delete=models.SET_NULL, null= True)
	summary = models.TextField(max_length=1000, help_text='Enter a brief description of Book')
	isbn = models.CharField('ISBN', max_length=13,help_text='13 character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
	genre = models.ManyToManyField(Genre, help_text='Select a genre for this book')


	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('book-detail', args=[str(self.id)])

	def display_genre(self):
		return ', '.join([ genre.name for genre in self.genre.all()[:3] ])
	display_genre.short_description = 'Genre'

class BookInstance(models.Model):
	"""docstring for BookInstance"""
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Undique id')
	book = models.ForeignKey('Book',on_delete=models.SET_NULL, null=True)	
	due_back = models.DateField(null=True, blank = True)

	LOAN_STATUS = (
		('m', 'Maintenance'),
		('o', 'On loan'),
		('a', 'Available'),
		('r', 'Reserved'),
	)

	status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='d', help_text='Availability')

	class Meta:
		ordering = ['due_back']


		"""docstring for Meta"""
	def __str__(self):
		return '{0} ({1})'.format(self.id,self.book.title)


class Author(models.Model):
		"""docstring for Author"""
		first_name = models.CharField(max_length=100)
		last_name = models.CharField(max_length=100)
		date_birth = models.DateField(null=True, blank=True)
		date_death = models.DateField('Died in..', null = True, blank=True)

		def get_absolute_url(self):
			return reverse('author-detail', args=[str(self.id)])

		def __str__(self):
			#return '%s, %s' % (self.last_name, 	self.first_name)
			return '{0} ({1})'.format(self.last_name,self.first_name)

newsite/catalog/views.py
from django.shortcuts import render
from .models import book, Author, BookInstance, Genre
from django.views import generic
# Create your views here.

def index(request):
	num_books=book.objects.all().count()
	num_instances= BookInstance.objects.all().count()
	num_instances_available = BookInstance.objects.filter(status__exact='a').count()
	num_authors=Author.objects.count()

	return render(
		request,
		'index.html',
		context={'num_books':num_books,'num_instances':num_instances,'num_instances_available':num_instances_available,'num_authors':num_authors},
    )

class BookListView(generic.ListView):
	model = book
	paginate_by = 10


class BookDetailView(generic.DetailView):
    model = book

newsite/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'books' %}">All books</a></li>
          <li><a href="">All authors</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}

      {% endblock %}
      {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                    {% endif %}
                    <span class="page-current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
      {% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

newsite/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Title: {{ book.title }}</h1>

<p><strong>Author:</strong> <a href="{% url 'author-detail' book.author.pk %}">{{ book.author }}</a></p>
<p><strong>Summary:</strong> {{ book.summary }}</p>
<p><strong>ISBN:</strong> {{ book.isbn }}</p> 
<p><strong>Language:</strong> {{ book.language }}</p>  
<p><strong>Genre:</strong> {% for genre in book.genre.all %}{{genre}}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

<div style="margin-left:20px;margin-top:20px">
<h4>Copies</h4>

{% for copy in book.bookinstance_set.all %}
<hr>
<p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
{% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
<p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>

{% endfor %}
</div>
{% endblock %}

newsite/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

newsite/catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em></p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}